on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        glium: ["", "glium-support"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --features '${{ matrix.glium }}'
      - run: cargo test --features '${{ matrix.glium }}'
      - run: cargo clippy --features '${{ matrix.glium }}' --no-deps -- -D warnings
      - run: cargo fmt -- --check
